### ISSUE TITLE
Python and JS version

### ISSUE THREAD

**Issue by DonaldTsang** [rinick/base2e15#2]
Python version would be pretty fun with this.
JS would be good for web situations.

**Comment by rinick** [comment]
split into 2 different tasks

**Comment by rinick** [comment]
@DonaldTsang 
let me know if you are going to use it very soon, if that's the case I will see if I can implement them quickly in these 2 days.

**Comment by DonaldTsang** [comment]
@rinick keep it in the backburner if you like, just figure that the python implementation should be relatively easy (I will make a sample), but the JS version would take time
